### ISSUE TITLE
[Feat] 허브 API 

### ISSUE THREAD

**Issue by bongbongbon** [noname29-sparta/Backend#1]
## TODO
- [x] 컨트롤러 작성
- [x] 도메인 파일 작성
- [x] 허브 CRUD 기능
- [x] 허브 Search 기능
